### ISSUE TITLE
Local config for project-catalogs.yml fails

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects-experimental/spring-cli#45]
Error is:
```
2022-12-02T08:32:40.988Z ERROR 30771 --- [main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'projectCatalogInitializer': Unable to read from path /home/jvalkealahti/.config/springcli/project-catalogs.yml
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1751) ~[spring:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring:6.0.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring:6.0.2]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring:6.0.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring:6.0.2]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring:6.0.2]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915) ~[spring:6.0.2]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring:6.0.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring:3.0.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring:3.0.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring:3.0.0]
	at org.springframework.cli.SpringCliApplication.main(SpringCliApplication.java:30) ~[spring:na]
Caused by: java.lang.RuntimeException: Unable to read from path /home/jvalkealahti/.config/springcli/project-catalogs.yml
	at org.springframework.cli.support.configfile.YamlConfigFile.read(YamlConfigFile.java:48) ~[na:na]
	at org.springframework.cli.support.configfile.UserConfig.getConfig(UserConfig.java:60) ~[na:na]
	at org.springframework.cli.config.SpringCliUserConfig.getProjectCatalogs(SpringCliUserConfig.java:163) ~[spring:na]
	at org.springframework.cli.config.ProjectCatalogInitializer.afterPropertiesSet(ProjectCatalogInitializer.java:45) ~[spring:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1797) ~[spring:6.0.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1747) ~[spring:6.0.2]
	... 15 common frames omitted
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (DataInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4821) ~[spring:2.14.1]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4723) ~[spring:2.14.1]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3714) ~[spring:2.14.1]
	at org.springframework.cli.support.configfile.YamlConfigFile.read(YamlConfigFile.java:46) ~[na:na]
	... 20 common frames omitted
```
We can't error at startup i.e. you have something stale or whatever is a reason.

**Comment by markpollack** [comment]
We need to catch exceptions coming from `YamlConfigFile` and have a better result handler, one that doesn't have to show the full stack trace.

**Comment by markpollack** [comment]
If there is an issue deserializing the configuration on startup, a warning message is now printed and the stacktrace is suppressed.

In this case, I corrupted the YAML file

```
$ spring
warning: Unable to read YAML file from path /home/mark/.config/springcli/project-catalogs.yml
spring:>
```
